

### This file is temporary. This is the query used on SPARQL-Anything to generate the D&D Ontology from xml files.


PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX fx: <http://sparql.xyz/facade-x/ns/>
PREFIX xyz: <http://sparql.xyz/facade-x/data/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dnd: <https://w3id.org/dnd5e/>


CONSTRUCT {
  ### D&D CLASS TRIPLES
?dndclass a owl:NamedIndividual ; rdfs:label ?name ;
    dnd:hitDice ?hitDice ;
    dnd:classProficiency ?classProficiency ;
      dnd:castsWith ?casterAbility .
  
  ### GENERAL D&D ONTOLOGY TRIPLES
  ?hitDice a owl:Class , owl:NamedIndividual ; a dnd:DiceType .
  ?classProficiency a owl:Class , owl:NamedIndividual ; a dnd:Ability .
  ?casterAbility a dnd:Ability .
  
}

WHERE {
  SERVICE <x-sparql-anything:> {
    fx:properties fx:location "https://raw.githubusercontent.com/kinkofer/FightClub5eXML/main/Sources/PlayersHandbook/class-druid-phb.xml" .
    [ a xyz:compendium , fx:root ;
                  rdf:_1 [ a xyz:class ; 
                  rdf:_1 [ a xyz:name ; rdf:_1 ?name ] ;
				  rdf:_2 [ a xyz:hd ; rdf:_1 ?hd] ;
                  rdf:_3 [ a xyz:proficiency ; rdf:_1 ?proficiency] ;
                  rdf:_4 [ a xyz:numSkills ; rdf:_1 ?numSkills] ;
				  rdf:_5 [ a xyz:spellAbility ; rdf:_1 ?spellAbility]          
      ] 
    ]
             
      BIND(IRI(CONCAT("https://w3id.org/dnd5e/",str(?name))) AS ?dndclass)
      BIND(IRI(CONCAT("https://w3id.org/dnd5e/d",str(?hd))) AS ?hitDice)
      BIND(IRI(CONCAT("https://w3id.org/dnd5e/",str(?proficiency))) AS ?classProficiency)
      BIND(IRI(CONCAT("https://w3id.org/dnd5e/",str(?spellAbility))) AS ?casterAbility)
      OPTIONAL {
        SERVICE <x-sparql-anything:> {
          fx:properties fx:content ?proficiency .
          fx:properties fx:txt.split ", " .
          FILTER(isLiteral(?cProf))
          FILTER(strlen(str(?proficiency))>0)
          ?a ?b ?cProf
          BIND(IRI(CONCAT("https://w3id.org/dnd5e/",str(?cProf))) AS ?classProficiency)
  }
  }
  }
}
